- hosts: ctrlplane_instances
  become: yes
  tasks:

  - name: Delay before start (15 seconds)
    pause:
      seconds: 15

  - name: start kubelet
    service:
      name: kubelet
      enabled: yes
      state: started

  - name: initialize K8S cluster
    shell: kubeadm init --apiserver-cert-extra-sans={{ ansible_ssh_host }} --apiserver-advertise-address={{ ctrl_plane_private_ip }} --pod-network-cidr={{ pod_network_cidr }}  --cri-socket unix:///run/containerd/containerd.sock

  - name: create /root/.kube directory
    file:
      path: /root/.kube
      state: directory
      mode: 0755

  - name: create /home/ec2-user/.kube directory
    file:
      path: /home/ec2-user/.kube
      state: directory
      mode: 0755

  - name: Copy config file to root and ec2-user home directories
    ansible.builtin.copy:
      remote_src: yes
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: /etc/kubernetes/admin.conf, dest: /root/.kube/config } 
      - { src: /etc/kubernetes/admin.conf, dest: /home/ec2-user/.kube/config } 

  - name: Wait 30 seconds
    pause:
      seconds: 30

  - name: Untaint the controlplane 
    shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

  - name: Installing Calico
    shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/tigera-operator.yaml

  - name: Download Calico custom-resources.yaml
    get_url:
      url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/custom-resources.yaml
      mode: '644'
      dest: ~/custom-resources.yaml
      validate_certs: no

  - name: Modify Calico custom-resources.yaml
    shell: sed -i "s#192.168.0.0/16#{{ pod_network_cidr }}#" ~/custom-resources.yaml

  - name: Install Calico custom-resources.yaml manifest
    shell: kubectl apply -f ~/custom-resources.yaml

